_target_: src.model.linprobe.LinearProbe
encoder:
  _target_: transformers.AutoModel.from_pretrained
  pretrained_model_name_or_path: microsoft/rad-dino
num_classes: ${dataset.num_classes}
embedding_dim: 768
freeze_encoder: true
pooling: cls
