_target_: src.logger.cometml.CometMLWriter
project_name: image-generation-papers
run_name: test
workspace: null # your cometml username or team name
run_id: null # set to resume a specific run
mode: offline # online, offline
log_code: false
log_graph: false
auto_metric_logging: false
auto_param_logging: false
log_dir: logs/${writer.project_name}/${writer.run_name}
