_target_: src.logger.wandb.WandBWriter
project_name: image-generation-papers
run_name: test
entity: null # your wandb username or team name
run_id: null # set to resume a specific run
mode: offline # online, offline, disabled, shared
save_code: false
log_dir: logs/${writer.project_name}/${writer.run_name}
